### ISSUE TITLE
File icons not loading?

### ISSUE THREAD

**Issue by asodugf12** [ryohidaka/kawaii-icons#5]
![image](https://github.com/ryohidaka/kawaii-icons/assets/91423016/b2a84417-0f75-4b4e-b004-c53d0001c1d3)

Tried clearing the icon cache, but that didn't work.

**Comment by ryohidaka** [comment]
@asodugf12 

Thank you for contacting us.
We have released `v0.3.1` which fixes this bug.

We hope you will check it.

**Comment by asodugf12** [comment]
It works now. ありがとうございました！
